services:
  efood-app:
    build:
      context: backend
    ports:
      - "8000:8000"

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER: myuser
      - POSTGRES_PASSWORD: mypassword
      - POSTGRES_DB: mydb
    ports:
      - "5432:5432"