services:
  efood-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./efood:/efood
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  frontend:
    build: ../frontend
    ports:
      - "80:80"
    depends_on:
      - api
    api:
      build: ./api
      ports:
        - "8080:8080"

  database:
    image: postgres:14.6-alpine
    environment: 
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass