# Generated by Django 4.2 on 2023-04-28 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='restaurant_images/')),
                ('name', models.CharField(max_length=250)),
                ('working_hours', models.TextField(validators=[django.core.validators.RegexValidator(message='Enter the hours of operation in the format "HH:MM - HH:MM".', regex='^([0-1][0-9]|2[0-3]):([0-5][0-9]) - ([0-1][0-9]|2[0-3]):([0-5][0-9])$')])),
            ],
        ),
    ]
