# Generated by Django 4.2 on 2023-04-24 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='working_hours',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='Enter the hours of operation in the format "HH:MM - HH:MM".', regex='^([0-1][0-9]|2[0-3]):([0-5][0-9]) - ([0-1][0-9]|2[0-3]):([0-5][0-9])$')]),
        ),
    ]
